package pojos;
// Generated Nov 24, 2018 1:19:53 PM by Hibernate Tools 4.3.1



/**
 * UserDomainProvider generated by hbm2java
 */
public class UserDomainProvider  implements java.io.Serializable {


     private String email;
     private String nama;
     private String password;

    public UserDomainProvider() {
    }

	
    public UserDomainProvider(String email) {
        this.email = email;
    }
    public UserDomainProvider(String email, String nama, String password) {
       this.email = email;
       this.nama = nama;
       this.password = password;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


