package pojos;
// Generated Nov 6, 2018 11:35:38 AM by Hibernate Tools 4.3.1



/**
 * Services generated by hbm2java
 */
public class Services  implements java.io.Serializable {


     private String domain;
     private Double harga;

    public Services() {
    }

	
    public Services(String domain) {
        this.domain = domain;
    }
    public Services(String domain, Double harga) {
       this.domain = domain;
       this.harga = harga;
    }
   
    public String getDomain() {
        return this.domain;
    }
    
    public void setDomain(String domain) {
        this.domain = domain;
    }
    public Double getHarga() {
        return this.harga;
    }
    
    public void setHarga(Double harga) {
        this.harga = harga;
    }




}


