package pojos;
// Generated Nov 15, 2018 11:03:11 AM by Hibernate Tools 4.3.1



/**
 * Services generated by hbm2java
 */
public class Services  implements java.io.Serializable {


     private String id;
     private String domain;
     private Double harga;
     private String namaPenjual;

    public Services() {
    }

	
    public Services(String id) {
        this.id = id;
    }
    public Services(String id, String domain, Double harga, String namaPenjual) {
       this.id = id;
       this.domain = domain;
       this.harga = harga;
       this.namaPenjual = namaPenjual;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getDomain() {
        return this.domain;
    }
    
    public void setDomain(String domain) {
        this.domain = domain;
    }
    public Double getHarga() {
        return this.harga;
    }
    
    public void setHarga(Double harga) {
        this.harga = harga;
    }
    public String getNamaPenjual() {
        return this.namaPenjual;
    }
    
    public void setNamaPenjual(String namaPenjual) {
        this.namaPenjual = namaPenjual;
    }




}


