package pojos;
// Generated Nov 1, 2018 11:49:46 AM by Hibernate Tools 4.3.1



/**
 * Services generated by hbm2java
 */
public class Services  implements java.io.Serializable {


     private String domain;

    public Services() {
    }

    public Services(String domain) {
       this.domain = domain;
    }
   
    public String getDomain() {
        return this.domain;
    }
    
    public void setDomain(String domain) {
        this.domain = domain;
    }




}


