package pojos;
// Generated Nov 15, 2018 11:03:11 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transaksi generated by hbm2java
 */
public class Transaksi  implements java.io.Serializable {


     private String id;
     private String domain;
     private Double harga;
     private String namaPenjual;
     private Date tanggalPembelian;

    public Transaksi() {
    }

	
    public Transaksi(String id) {
        this.id = id;
    }
    public Transaksi(String id, String domain, Double harga, String namaPenjual, Date tanggalPembelian) {
       this.id = id;
       this.domain = domain;
       this.harga = harga;
       this.namaPenjual = namaPenjual;
       this.tanggalPembelian = tanggalPembelian;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getDomain() {
        return this.domain;
    }
    
    public void setDomain(String domain) {
        this.domain = domain;
    }
    public Double getHarga() {
        return this.harga;
    }
    
    public void setHarga(Double harga) {
        this.harga = harga;
    }
    public String getNamaPenjual() {
        return this.namaPenjual;
    }
    
    public void setNamaPenjual(String namaPenjual) {
        this.namaPenjual = namaPenjual;
    }
    public Date getTanggalPembelian() {
        return this.tanggalPembelian;
    }
    
    public void setTanggalPembelian(Date tanggalPembelian) {
        this.tanggalPembelian = tanggalPembelian;
    }




}


