package pojos;
// Generated Nov 1, 2018 11:49:46 AM by Hibernate Tools 4.3.1



/**
 * Transaksi generated by hbm2java
 */
public class Transaksi  implements java.io.Serializable {


     private String history;

    public Transaksi() {
    }

    public Transaksi(String history) {
       this.history = history;
    }
   
    public String getHistory() {
        return this.history;
    }
    
    public void setHistory(String history) {
        this.history = history;
    }




}


