package pojos;
// Generated Nov 15, 2018 11:03:11 AM by Hibernate Tools 4.3.1



/**
 * UserCalonPembeli generated by hbm2java
 */
public class UserCalonPembeli  implements java.io.Serializable {


     private String email;
     private String nama;
     private String password;

    public UserCalonPembeli() {
    }

	
    public UserCalonPembeli(String email) {
        this.email = email;
    }
    public UserCalonPembeli(String email, String nama, String password) {
       this.email = email;
       this.nama = nama;
       this.password = password;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


